# Data settings
data:
  num_workers: 4
  train_batch_size: 4
  val_batch_size: 14
  num_samples: 8
  interval: 16
  data_path: /irip/tanlingfeng_2020/data/ff++/frames
  list_path: datasets/ffpp
  img_quality: LQ
  img_size: 320
  random_sample: True


# Training settings
training:
  resume: /irip/tanlingfeng_2020/v2g/logs/PartialGCN/HQ/lightning_logs/version_5309/checkpoints/val_auc-epoch_002-loss_0.337-acc_0.97881-auc_0.99524.ckpt
  save_dir: logs/
  precision: 32
  num_epochs: 30
  grad_accumulate: 1
  early_stop_patience: 10
  val_interval: 1
  log_interval: 30
  clip_grad_val: 5.0
  optim:
    # choose 'adam' or 'sgd'
    optimizer: adam
    lr: 2.0e-4
    min_lr: 2.0e-6
    weight_decay: 0.01
    # eps: 1.0e-8
    eps: 1.0e-3
    momentum: 0.9

    sche:
      # choose 'plateau' or 'step' or 'cosine'
      sche_type: plateau
      # used for 'step'
      decay_epochs: 5
      gamma: 0.3
      # used for 'plateau'
      patience_epochs: 2
      factor: 0.3
  
  # Model settings
  model:
    model_name: V2G
    num_classes: 2